openapi: 3.1.0
info:
  title: Tipper Self Register API
  description: API documentation with standardized success and error envelopes.
  version: 1.0.0

tags:
  - name: public
    description: "Open endpoints for authentication and onboarding"
  - name: tipper
    description: "\"/tipper\"-related APIs"
  - name: ops
    description: "\"/ops\"-related APIs"

paths:
  /public/v1/tipper/register/send-otp:
    post:
      summary: Send Registration OTP
      tags:
        - public
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "john@doe.com"
      responses:
        '200':
          description: General success response with data envelope.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralSuccessEnvelope'
                example:
                  success: true
                  data: {
                    message: "Success"
                  }
        '400':
          $ref: '#/components/responses/BadRequest'

  /public/v1/tipper/register/validate-otp:
    post:
      summary: Validate Registration OTP
      tags:
        - public
      description: Verifies the OTP sent to the user's email before allowing full registration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - otp
              properties:
                email:
                  type: string
                  format: email
                  example: "john@doe.com"
                otp:
                  type: string
                  description: "The 6-digit code received by the user"
                  example: "123456"
      responses:
        '200':
          description: OTP is valid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralSuccessEnvelope'
                example:
                  success: true
                  data:
                    token: "eyJ0eXA..."
        '400':
          description: Invalid or expired OTP.
          $ref: '#/components/responses/BadRequest'

  /public/v1/tipper/register:
    post:
      summary: Complete Registration
      tags:
        - public
      parameters:
        - name: X-REGISTER-ACCESS-TOKEN
          in: header
          description: Access token from /validate-otp API
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralSuccessEnvelope'
                example:
                  success: true
                  data:
                    id: "934eaa32-be5f-4ee1-a24d-7549aba722bc"
                    tipperStaffApplication: {
                      id: "962a29b9-80aa-4365-aa23-6cfa4acbe227",
                      status: "INCOMPLETE"
                    }
        '400':
          $ref: '#/components/responses/BadRequest'

  /tipper/v1/merchants:
    get:
      summary: Search eligible merchants in tipper flow
      tags:
        - tipper
      parameters:
        - name: searchKeyword
          in: query
          required: false
          schema:
            type: string
          example: "foo"
      responses:
        '200':
          $ref: '#/components/responses/MerchantListResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /tipper/v1/applications/latest:
    get:
      summary: Get Latest Application Status
      tags:
        - tipper
      description: Retrieves the most recent application associated with the authenticated tipper staff, including its current workflow status.
      responses:
        '200':
          description: Successfully retrieved the latest application.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralSuccessEnvelope'
                example:
                  success: true
                  data:
                    id: "962a29b9-80aa-4365-aa23-6cfa4acbe227"
                    status: "PENDING_REVIEW_BUSINESS_OPS"
                    documents: {
                      KTP: {
                        url: "image-url.com",
                        ocrResult: {
                          address: string,
                          birthPlace: string,
                          bloodType: string,
                          city: string,
                          dateOfBirth: string,
                          expiryDate: string,
                          gender: string,
                          isSuspicious: true,
                          maritalStatus: string,
                          name: string,
                          nationality: string,
                          nik: string,
                          occupation: string,
                          province: string,
                          region: string,
                          religion: string,
                          rt: string,
                          rw: string,
                          suspiciousReasons: [
                            string
                          ],
                          village: string,
                          message: [
                            string
                          ],
                          runtime_log: string,
                          success: string
                        }
                      },
                      NPWP: {
                        url: "image-url.com",
                        ocrResult: {
                          address: string,
                          name: string,
                          nik: string,
                          npwp: string,
                          npwpValid: true,
                          taxBranch: string,
                          taxType: string,
                          taxPayerStatus: string,
                          message: [
                            string
                          ],
                          runtime_log: string,
                          success: string
                        }
                      },
                      COMPANY_CARD: {
                        url: "image-url.com"
                      }
                    }
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: No application found for this user.
          $ref: '#/components/responses/NotFound'

  /tipper/v1/applications/{id}/documents/{type}:
    post:
      summary: Upload Application Document
      tags:
        - tipper
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "APP-123"
        - name: type
          in: path
          required: true
          description: "e.g., KTP, NPWP, PROFILE, COMPANY_CARD"
          schema:
            type: string
          example: "KTP"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The document file to upload
      responses:
        '200':
          description: Uploaded document.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralSuccessEnvelope'
                example:
                  success: true
                  data:
                    id: "962a29b9-80aa-4365-aa23-6cfa4acbe227"
                    documentType: "[KTP|NPWP|PROFILE|COMPANY_CARD]"
                    ocrResult: {
                      address: string,
                      birthPlace: string,
                      bloodType: string,
                      city: string,
                      dateOfBirth: string,
                      expiryDate: string,
                      gender: string,
                      isSuspicious: true,
                      maritalStatus: string,
                      name: string,
                      nationality: string,
                      nik: string,
                      occupation: string,
                      province: string,
                      region: string,
                      religion: string,
                      rt: string,
                      rw: string,
                      suspiciousReasons: [
                        string
                      ],
                      village: string,
                      message: [
                        string
                      ],
                      runtime_log: string,
                      success: string
                    }
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralSuccessEnvelope'
                example:
                  success: false
                  error:
                    type: "SatpamValidationError"
                    message: {
                      file: {
                        file: "file must be an image."
                      }
                    }

  /tipper/v1/applications/{id}/submit:
    post:
      summary: Submit Application
      tags:
        - tipper
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "APP-123"
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'

  /ops/v1/tipper/staffs/{id}/application-logs:
    post:
      summary: Application logs by tipper staff id
      tags:
        - ops
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "APP-123"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralSuccessEnvelope'
              example:
                summary: Application logs
                value:
                  - id: "id"
                    tipperStaffApplicationId: "tipperStaffApplicationId"
                    updaterId: "updaterId"
                    updaterRole: "[USER|ADMIN]"
                    action: "[CREATE_APPLICATION|SUBMIT_APPLICATION|UPDATE]"
                    reason: "remarks"
                    delta: "<delta in json>"
                    createdAt: ""
                    updatedAt: ""
                  - id: "id"
                    tipperStaffApplicationId: "tipperStaffApplicationId"
                    updaterId: "updaterId"
                    updaterRole: "[USER|ADMIN]"
                    action: "[CREATE_APPLICATION|SUBMIT_APPLICATION|UPDATE]"
                    reason: "remarks"
                    delta: "<delta in json>"
                    createdAt: ""
                    updatedAt: ""

components:
  responses:
    SuccessResponse:
      description: General success response with data envelope.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralSuccessEnvelope'
    
    MerchantListResponse:
      description: A list of merchants wrapped in a standard success envelope.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantEnvelope'

    Created:
      description: The resource was created successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatedEnvelope'

    BadRequest:
      description: The request was invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'

    Unauthorized:
      description: Authentication failed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'

    NotFound:
      description: The requested resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'

    ServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'

  schemas:
    # --- BUSINESS ENTITIES ---
    Merchant:
      type: object
      properties:
        id: { type: string, example: "ece3a9b7-8fab-43c8-9567-253687054462" }
        name: { type: string, example: "Jaya Elektronik" }

    # --- SUCCESS ENVELOPES ---
    GeneralSuccessEnvelope:
      type: object
      properties:
        success: { type: boolean, example: true }
        data:
          type: object
          properties:
            message: { type: string, example: "Operation completed successfully" }

    MerchantEnvelope:
      type: object
      properties:
        success: { type: boolean, example: true }
        data:
          type: array
          items:
            $ref: '#/components/schemas/Merchant'

    CreatedEnvelope:
      type: object
      properties:
        success: { type: boolean, example: true }
        data:
          type: object
          properties:
            id: { type: string, example: "12345" }
            message: { type: string, example: "Resource created successfully" }

    # --- ERROR ENVELOPES ---
    ErrorEnvelope:
      type: object
      properties:
        success: { type: boolean, example: false }
        error:
          $ref: '#/components/schemas/ErrorModel'

    # --- DATA MODELS ---
    ErrorModel:
      type: object
      properties:
        type: { type: string, example: "BadRequest|<error messaging>" }
        message: { type: string, example: "<error message in bahasa indonesia>" }

    LoginRequest:
      type: object
      properties:
        email: { type: string, example: "johndoe@example.com" }
        password: { type: string, format: password, example: "P@ssword123" }

    LoginResponse:
      type: object
      properties:
        success: { type: boolean, example: true }
        data:
          type: object
          properties:
            token: { type: string, example: "eyJ0eXA..." }
            showTncAgreement: { type: boolean, example: false }
            application:
              type: object
              properties:
                status:
                  type: string
                  description: "Application status"
                  enum:
                    - INCOMPLETE
                    - PENDING_REVIEW_ANTI_FRAUD
                    - PENDING_REVIEW_BUSINESS_OPS
                    - APPROVED
                    - REJECTED
                    - BLOCKED
                  example: "INCOMPLETE"

    RegistrationRequest:
      type: object
      properties:
        email: { type: string, example: "johndoe@example.com" }
        password: { type: string, format: password, example: "P@ssword123" }